### ISSUE TITLE
Asset name should be automatically constructed

### ISSUE THREAD

**Issue by puck** [AssetTracker/rt-extension-assettracker#1]
Wishlist item:

For assets such as HDDs, motherboards etc the asset name should be allowed to be assembled use custom fields, ideally automatically.

In my example, the maker, model and serial number should be used.  Otherwise I'd just repeat that information needlessly.

**Comment by chakatodd** [comment]
puck,

You can write a scrip to set the name after the custom field is created. 

I could add an option to automatically assign a unique ID to an asset so that you wouldn't have to think up a unique, default name.

**Comment by puck** [comment]
Hey Todd,

Yeah, both of those sound like good ideas.

**Comment by pr3sidentspence** [comment]
I'd very much like the auto-name.

**Comment by pr3sidentspence** [comment]
Hmmm... thought I posted this last week. I think I found a solution to this.

I don't care what the name is, as long as it increments and meets the uniqueness requirement. The odds of two new asset pages being loaded at the same millisecond seem pretty low, so I decided to use unix time as my unique name.

The change was silly easy once I found where to do it. Under EditBasics simply replace "new asset" with time()

**Comment by pr3sidentspence** [comment]
Whoops, it didn't like just a number, so I preceded it with 'PAR' which was the format we were previously using, inherited from our old tracking software, infraenterprise. 

so replace 'new asset' with 'PAR' . time()

(or whatever other string you like)

**Comment by btb** [comment]
Confirmed that scrips work well for this purpose

**Comment by puck** [comment]
For anyone who finds this issue in the future, I've written an extensions which allows dynamically generating an asset name using custom fields: https://github.com/catalyst-cloud/rt-extension-assetautoname
