### ISSUE TITLE
Custom Fields for Assets in RT 4.0.2

### ISSUE THREAD

**Issue by smandolare** [AssetTracker/rt-extension-assettracker#11]
When creating custom fields and assigning them to Asset Types, changes will take effect on all Asset Types. Currently unable to assign various different Custom Fields to different Asset Types in RT 4.0.2.

**Comment by chakatodd** [comment]
Any "Asset Type" CF in AT is equivalent to a "Queue" CF in RT. Once you create an "Asset Type" CF you can use the "applies to" menu to assign it to different asset types. Then when you are editing/adding an asset type (not an asset) you can populate the CF. My guess is that pretty much all Queue CFs are meant to be global and all Asset Type CFs are meant to be global too.

If you continue to have a problem please send some screenshots to the at-users mailing list. groups.google.com/group/at-users
