### ISSUE TITLE
Broken link to "Asset Types" in Admin menu

### ISSUE THREAD

**Issue by dentm42** [AssetTracker/rt-extension-assettracker#15]
The link associated with the menu heading "Asset Types" in the Asset Admin menu is broken.  Instead of directing to "/AssetTracker/Admin/Types" it directs to "/Admin/Types".

FIX:

<pre>
186c186
<                                      path => "/Admin/$type/" );

---
>                                      path => "/AssetTracker/Admin/$type/" );
</pre>

**Comment by dentm42** [comment]
diff with fixed formatting:

<pre>
186c186
&lt;                                      path =>  "/Admin/$type/" );
---
&gt;                                      path => "/AssetTracker/Admin/$type/" );
</pre>

**Comment by pr3sidentspence** [comment]
What file is this in?

**Comment by dentm42** [comment]
It's in: html/Callbacks/AssetTracker/Elements/Tabs/Privileged

See also: https://github.com/dentm42/rt-extension-assettracker/commit/6d736903763c40d6eb405b1be984bc888057cfe2
