### ISSUE TITLE
Asset OBJECT not loading to associate CUSTOM FIELDS (AT 2.0.2b)

### ISSUE THREAD

**Issue by dentm42** [AssetTracker/rt-extension-assettracker#16]
PROBLEM:

When attempting to edit CUSTOM FIELDS associated with an ASSET TYPE, the specific asset type object is not loaded and CUSTOM FIELDS are associated with all objects.

FIX:  FILE: .../html/AssetTracker/Admin/Elements/ObjectCustomFields

Move(<code>  $Object->Load($id) || Abort(loc("Couldn't load object [_1]", $id)); </code>  (Line 93) outside of "IF" block.  Before/after shouldn't matter.  I moved it after so that at least the menu tabs will load and allow easier navigation.

**Comment by dentm42** [comment]
Actually, moving it into the "if ($id)" block at about line 98 is a better solution.

**Comment by dpajin** [comment]
Hi dentm42,

I have tried with your proposed fix, but it doesnt work for me. Any change over custom fields is applied over all asset types. The title on the page /AssetTracker/Admin/Types/CustomFields.html?SubType=RTx::AssetTracker::Asset&id=2, is missing a Name of the Asset Type, it is just "Edit Custom Fields for "?
I am using latest version od Asset tracker and RT4.0.4!

Thank you in advance!

**Comment by dentm42** [comment]
After making the update, did you clear the mason cache?

**Comment by dpajin** [comment]
No, I didn't know I should do that! After clearing the mason cache with the "rm -rf /opt/rt4/var/mason_data/obj/*" it is now working. 

Thank you very much for your help!
