### ISSUE TITLE
Asset Types not showing up in "Basic Edit"

### ISSUE THREAD

**Issue by dentm42** [AssetTracker/rt-extension-assettracker#17]
I hit a weird problem with Asset Types not showing up in the "Basic Edit" screen (Modify Asset).

I traced the problem down to html/AssetTracker/Elements/SelectType  - specifically the conditional <code>unless ($session{'see_in_types'}) {</code> I see what you're trying to do in not "unnecessarily" reloading the list of asset types.  The problem comes in if the list of available asset types changes (new types added, others removed) during the same session.  When this happens, the updates don't get seen.

There is a similar conditional in html/AssetTracker/Elements/SelectNewAssetType.

I don't see any precedent for this type of use of the session data in the original RT code - and, as mentioned, it causes problems when the list of asset types changes.

I recommend removing the conditional (I've done so in my own install).  I am curious though, is there any reason to be storing this list as session data anyway - or did that just happen to be a convenient storage bin?

I have to say --- great work!  I really like both RT and now, with the addition of AT, I'm really seeing potential for my purposes!  

I hope there's no anxiety over all the "bug reports"... I certainly don't mean to step on toes... I just happen to be getting things up and going with my install and figured I'd share what I've leaned and help out where I can. 

-- Matt

**Comment by btb** [comment]
this fix was applied
