### ISSUE TITLE
Error running RTHOME=/path/to/rt perl Makefile.PL WARNING: Setting VERSION via file 'lib/RTx/AssetTracker.pm' failed

### ISSUE THREAD

**Issue by pr3sidentspence** [AssetTracker/rt-extension-assettracker#2]
Could not eval '
                package ExtUtils::MakeMaker::_version;
                no strict;
                BEGIN { eval {
                    # Ensure any version() routine which might have leaked
                    # into this package has been deleted.  Interferes with
                    # version->import()
                    undef *version;
                    require version;
                    "version"->import;
                } }

```
            local $VERSION;
            $VERSION=undef;
            do {
                use version; our $VERSION = version->declare("2.0.0_2");
            };
            $VERSION;
        ' in lib/RTx/AssetTracker.pm: Can't locate object method "declare" via package "version" at (eval 15) line 16, <$fh> line 22.
```

Cannot determine perl version info from lib/RTx/AssetTracker.pm
Cannot determine author info from lib/RTx/AssetTracker.pm
Cannot determine license info from lib/RTx/AssetTracker.pm
Using RT configuration from /opt/rt3/lib/RT.pm:
./etc   => /opt/rt3/local/plugins/RTx-AssetTracker/etc
./html  => /opt/rt3/local/plugins/RTx-AssetTracker/html
./lib   => /opt/rt3/local/plugins/RTx-AssetTracker/lib
./po    => /opt/rt3/local/plugins/RTx-AssetTracker/po
./sbin  => /opt/rt3/local/plugins/RTx-AssetTracker/sbin
For first-time installation, type 'make initdb'.
Could not eval '
                package ExtUtils::MakeMaker::_version;
                no strict;
                BEGIN { eval {
                    # Ensure any version() routine which might have leaked
                    # into this package has been deleted.  Interferes with
                    # version->import()
                    undef *version;
                    require version;
                    "version"->import;
                } }

```
            local $VERSION;
            $VERSION=undef;
            do {
                use version; our $VERSION = version->declare("2.0.0_2");
            };
            $VERSION;
        ' in lib/RTx/AssetTracker.pm: Can't locate object method "declare" via package "version" at (eval 32) line 16, <$fh> line 22.
```

WARNING: Setting VERSION via file 'lib/RTx/AssetTracker.pm' failed
 at /usr/lib/perl5/5.8.8/ExtUtils/MakeMaker.pm line 571
Writing Makefile for RTx::AssetTracker

**Comment by chakatodd** [comment]
Do you have the perl module "version" installed?

**Comment by pr3sidentspence** [comment]
Hi Todd,

Yes. 0.76

Mike

**Comment by pr3sidentspence** [comment]
Accidentally closed the issue, sorry I'm new to github.

**Comment by chakatodd** [comment]
What version of RT? You might want to try upgrading the "version" module.

**Comment by pr3sidentspence** [comment]
RT 3.8.4.

Upgraded. Will try installing again.

**Comment by pr3sidentspence** [comment]
Upgrading version resolved this issue.

**Comment by chakatodd** [comment]
Great. I'll update the version requirement for version. :)
