### ISSUE TITLE
Asset import fails

### ISSUE THREAD

**Issue by pr3sidentspence** [AssetTracker/rt-extension-assettracker#20]
Duplicate:
1) Download an importable spreadsheet for one single asset.
2) Make a simple change to the file, either in excel or a text editor (I chose to change a status from "dr" to "production"
3) Save file
4) At ../AssetTracker/Tools/Import.html select and try to import the file

Result:

```
Asset import errors. No changes were made.
Asset #123 not updated:
```

rt.log:

<pre>
[Wed Nov 30 21:28:51 2011] [error]: Asset import error. Rolling back DB transactions. (/opt/rt4/local/plugins/RTx-AssetTracker/lib/RTx/AssetTracker/Assets_Overlay.pm:2527)
[Wed Nov 30 21:28:51 2011] [debug]: /AssetTracker/Elements/Tabs calls old style callback, use $m->callback (/opt/rt4/share/html/Elements/Callback:51)
[Wed Nov 30 21:28:51 2011] [warning]: CurrentAssetSearchHashCurrentUserSelectQueue---12---CreateTicket---0_session_last_updateassetscreate_in_typesActions_session_idmy_rt_portletssee_in_typesi at /opt/rt4/local/plugins/RTx-AssetTracker/html/Callbacks/AssetTracker/Elements/Tabs/Privileged line 11. (/opt/rt4/local/plugins/RTx-AssetTracker/html/Callbacks/AssetTracker/Elements/Tabs/Privileged:11)

</pre>

Note: I have to enter the url for the import page manually, I can't find a way to get there in the UI.

**Comment by btb** [comment]
I can't reproduce this. Maybe more information would help.
