### ISSUE TITLE
Searching for Links doesn't work

### ISSUE THREAD

**Issue by JvdW** [AssetTracker/rt-extension-assettracker#21]
I just tried to do a search using ComponentOf but it doesn't work.
Looking at the sql that ends up in the database I can see why it wouldn't work but I can't figure out how to fix it.
The same search type works correctly for tickets but not for Assets.

/\* Formatted on 1-12-2011 15:49:10 (QP5 v5.163.1008.3004) */
SELECT COUNT (DISTINCT main.id)
  FROM AT_Assets main JOIN Links Links_1 ON (Links_1.LocalBase = main.URI)
 WHERE ( (Links_1.TYPE = 'ComponentOf' AND Links_1.LocalTarget = '1321'))

Problem area is main.URI which isn't a number but a string at://example.com/asset/1321

**Comment by dentm42** [comment]
I think the search is performing properly, just not as expected.  From what I can see, the search element should be entered as the entire URI and not just the asset #.  Perhaps someone else can explain why this would be the case.  My speculation would be it has to do something with AT being separate from RT at one point and being brought in as a module.

Perhaps start a discussion on the mailing list and someone else knows why this would be the case and/or if there's a desire to change the behavior.

**Comment by btb** [comment]
this is because just a number by itself is interpreted as a ticket #, so if you had an asset linked to ticket # 1321, then it would be found by that search (I think) perhaps this behavior could be changed but I'm not sure.
