### ISSUE TITLE
at-REST

### ISSUE THREAD

**Issue by JvdW** [AssetTracker/rt-extension-assettracker#22]
I'm using at-rest with rt-4.0.2 and having problems with some request returning an error and others working OK.
The following returns an error:
rt show asset/890
with the error: rt: Malformed RT response from http://rt.example.com
That doesn't tell me much more despite the RTDEBUG=3 setting suggested.
Adding a couple of extra DEBUG(3, $xxx); gives me the idea that RT/4.0.2 200 Ok isn´t present and that is the reason of the Malformed RT respons. Looking at the code in /REST/ doesn´t give a clue since the asset part looks like a clone of the ticket part.

**Comment by btb** [comment]
It should work with the REST interface now integrated into the main assettracker repository
