### ISSUE TITLE
Installing problems of asset on rt 4.0.2

### ISSUE THREAD

**Issue by catalinp** [AssetTracker/rt-extension-assettracker#23]
Hi
I am a new user of rt. I tried to install asset: tracker and I received the following error:
Working with:
Type:   mysql
Host:   localhost
Name:   rt4
User:   rt-user
DBA:    rt-user
Now populating database schema.
DBD::mysql::st execute failed: Table 'AT_Types' already exists at /opt/rt4/sbin/../lib/RT/Handle.pm line 517.
...returned with error: 65280
make: **\* [initdb] Error 2

What I can to do , to solve the problem. Thanks

**Comment by chakatodd** [comment]
You didn't provide very much information, but the error suggests that
some or all of the AT tables already exist, so you must have installed
AT previously. Perhaps you should be following the upgrade
instructions?

Also, all AT support is given on the at-users mailing list, so please
take any further questions there. Thanks!

groups.google.com/group/at-users

On Wed, Dec 14, 2011 at 5:39 PM, catalinp
reply@reply.github.com
wrote:
