### ISSUE TITLE
HTML code in front page on RT 4.0.6

### ISSUE THREAD

**Issue by torrentalle** [AssetTracker/rt-extension-assettracker#28]
I have installer rt-extension-assettracker on rt 4.0.6 and i get this HTML code in front page, near "new asset  of type" button

<LABEL ACCESSKEY="9"> <SELECT NAME ="Type" onchange="document.CreateAssetOfType.submit()" class="select-assettype"> </SELECT> </LABEL> 

Here there's a screenshoot
http://files.muellers.ms/rt4-assettracker.png

**Comment by chakatodd** [comment]
You should ask on the Google group at-users.

https://groups.google.com/forum/?hl=en&fromgroups#!forum/at-users

**Comment by zladuric** [comment]
Specifically, here is a thing that worked for me on 4.0.6:
https://groups.google.com/forum/?hl=en&fromgroups=#!topic/at-users/qmgu-EO_-ro

**Comment by btb** [comment]
see https://github.com/chakatodd/rt-extension-assettracker/pull/32
