### ISSUE TITLE
HTML Injection into Localized Strings

### ISSUE THREAD

**Issue by kaistlin** [AssetTracker/rt-extension-assettracker#31]
Hi there,
Thank you for all your hard work.  My group is considering starting to use this, but before we do, we were wondering if you had plans to update it to work with RT 4.0.6 and beyond.  From what we've read, 4.0.6 disabled HTML injection into localized strings, which AT does.  

Thanks again.
-Elric

**Comment by btb** [comment]
see https://github.com/chakatodd/rt-extension-assettracker/pull/32
