### ISSUE TITLE
"New Asset of Type" dropdown

### ISSUE THREAD

**Issue by SilkBC** [AssetTracker/rt-extension-assettracker#36]
Installed from latest git download of "Master" branch.  The "New Asset Of Type" button is present, but no example assets configured.  Added an Asset Type called "Computer".  The "New Asset of Type" button is there, but instead of a dropdown letting me choose an asset type, the HTML code is displayed:

<LABEL ACCESSKEY="9"> <SELECT NAME ="Type" onchange="document.CreateAssetOfType.submit()" class="select-assettype"> <OPTION VALUE="1" 0> Computers </OPTION> </SELECT> </LABEL>

EDIT: I am running Request Tracker 3.8

**Comment by btb** [comment]
see https://github.com/chakatodd/rt-extension-assettracker/pull/32

**Comment by SilkBC** [comment]
That fixed it.  Thanks! :-)
