### ISSUE TITLE
AT UI elements do not appear in RT4.

### ISSUE THREAD

**Issue by pr3sidentspence** [AssetTracker/rt-extension-assettracker#4]
AT UI elements do not appear in RT4.

**Comment by jonahwh** [comment]
This is a very important issue - after upgrading to RT4, Asset Tracker is essentially read-only. We can see current assets, but cannot add any new ones!

**Comment by olaadejnr** [comment]
Installed Asset Tracker successfully on RT4 (fresh). No Graphic User Interface on the RT website.

please help.

**Comment by tbrumm** [comment]
think it is not yet rt 4 compatible!

**Comment by olaadejnr** [comment]
When is the new version that would be compatible with RT coming out.

-----Original Message-----

**Comment by pr3sidentspence** [comment]
I have tried the update that Todd committed in the last week or so. AssetTracker UI elements now show in RT4.0.2.
