### ISSUE TITLE
AssetTracker import error - foo.xls

### ISSUE THREAD

**Issue by studogg** [AssetTracker/rt-extension-assettracker#40]
Working on setting up AssetTracker. Exporting to spreadsheet works fine. But importing by default tries to open foo.xls.htm. It doesn't allow to select a file to import.

The error that follows is:
An internal RT error has occurred. Your administrator can find more details in RT's log files.

Thanks

stewart

**Comment by btb** [comment]
if this problem still occurs, please attach the log file
