### ISSUE TITLE
could not find component for path '/l_unsafe' 

### ISSUE THREAD

**Issue by yerdobe** [AssetTracker/rt-extension-assettracker#44]
Hi,

Hopping to find an answer to a problem I can not solve on my own. I have install in rt-8.8.11, the plugin RTx::AssetTracker, version 2.0.0_2. The installation went well excepted for 3 warnings, that may or may not be important:

rt-extension-assettracker-master # RTHOME=/var/www/localhost/htdocs/followup/rt-3.8.11 perl Makefile.PL
Cannot determine perl version info from lib/RTx/AssetTracker.pm
Cannot determine author info from lib/RTx/AssetTracker.pm
Cannot determine license info from lib/RTx/AssetTracker.pm
Using RT configuration from /var/www/localhost/htdocs/followup/rt-3.8.11/lib/RT.pm:
./etc   => //var/www/localhost/htdocs/followup/rt-3.8.11/local/plugins/RTx-AssetTracker/etc
./html  => //var/www/localhost/htdocs/followup/rt-3.8.11/local/plugins/RTx-AssetTracker/html
./lib   => //var/www/localhost/htdocs/followup/rt-3.8.11/local/plugins/RTx-AssetTracker/lib
./po    => //var/www/localhost/htdocs/followup/rt-3.8.11/local/plugins/RTx-AssetTracker/po
./sbin  => //var/www/localhost/htdocs/followup/rt-3.8.11/local/plugins/RTx-AssetTracker/sbin
For first-time installation, type 'make initdb'.
Writing Makefile for RTx::AssetTracker
Writing MYMETA.yml and MYMETA.json

After setting the RTHOME variable I run the next three commands:

make
make install
make initdb

I added "Set(@Plugins,(qw(RTx::AssetTracker)));" in etc/RT_SiteConfig.pm and restarted the web server. 

When I click the Asset button I got this error:

"could not find component for path '/l_unsafe' "

Is anyone aware of what I did wrong? Any info is welcome.

Thanks,

Philippe

**Comment by btb** [comment]
you need to upgrade to rt 3.8.12 or later
