### ISSUE TITLE
Asset Import Fails (RT 4.0.2)

### ISSUE THREAD

**Issue by RyanFrantz** [AssetTracker/rt-extension-assettracker#6]
RT 4.0.2
AT: 2.0.0b2 (with patches provided by Todd for RT4)
OS: CentOS 5

I can't import new assets, only update current assets via the Import.html page.  I see the following in my messages file:

Aug 22 22:26:56 ryan-laptop RT: ---#012- 0#012-#012  - Asset import errors. No changes were made.#012  - 'Asset # not updated: Permission denied'#012  - 'Asset # not updated: Permission denied' (/opt/rt4/local/plugins/RTx-AssetTracker/html/AssetTracker/Tools/Import.html:46)
Aug 22 22:26:56 ryan-laptop RT: create_in_typesCurrentAssetSearchHashCurrentUser_session_idActionsSelectQueue---12---CreateTicket---0my_rt_portlets at /opt/rt4/local/plugins/RTx-AssetTracker/html/Callbacks/AssetTracker/Elements/Tabs/Privileged line 11. (/opt/rt4/local/plugins/RTx-AssetTracker/html/Callbacks/AssetTracker/Elements/Tabs/Privileged:11)

I checked the Import.html page's code and see that it checks that the user has the right named 'AssetImport' (line 46).  I don't see that right exposed anywhere (i.e. Global->User Rights; Tools->Configuration-Asset Types->Servers->User Rights).  I tried modifying that line of code to look for the right 'CreateAsset' but got the same results as above.

Ryan

**Comment by btb** [comment]
It sounds like you were trying to create assets with an id number. The spreadsheet should have 'new' in the id column for new assets and an asset id will be automatically assigned.
