### ISSUE TITLE
Why *_ATOverlay.pm?

### ISSUE THREAD

**Issue by tbrumm** [AssetTracker/rt-extension-assettracker#69]
Hi Brad,
why you use CustomField_ATOverlay.pm instead of CustomField_Overlay.pm? If i try to open AT Libs from CLI Code, i get some errors in this case. Would it be better to use it in RT way?

Torsten

**Comment by btb** [comment]
RT's _Overlay.pm mechanism was never meant to be used by distributed
extensions, and causes problems when used that way. Instead the code should
be loaded when the extension itself is loaded. CLI code needs to make sure it also loads needed plugins.

http://www.gossamer-threads.com/lists/rt/devel/117276?do=post_view_flat#117276
