### ISSUE TITLE
Non-Superusers Can't Access Assets

### ISSUE THREAD

**Issue by RyanFrantz** [AssetTracker/rt-extension-assettracker#7]
RT 4.0.2
AT: 2.0.0b2 (with patches provided by Todd for RT4)
OS: CentOS 5

After a privileged (non-superuser, though) user creates an asset, he can not access the asset.  The following page:

**http://<myRtInstance>/AssetTracker/Asset/Display.html?id=4**

throws the following error:

```Can't call method "MembersObj" on an undefined value at /usr/local/rt/local/plugins/RTx-AssetTracker/html/AssetTracker/Asset/Elements/ShowPeople line 52.'''

This does _NOT_ occur for the superuser; he can access the asset just fine.  I verified that I have assigned _ALL_ rights to my users with respect to assets.

I'm not certain but I think that the method can't be called because the object $group isn't populated properly due to some permission issue.  I can't figure out what that permission is, if indeed that's the case.

**Comment by RyanFrantz** [comment]
I've run some tests and found that the issue definitely is related to $group in ShowPeople.  If I replace:

%     my $GroupMembersCount = $Asset->$group->MembersObj->Count();

with

%     my $GroupMembersCount = '0';
%     print "FOOBAR: $group\n";

I see 'AdminRoleGroup' and 'OwnerRoleGroup' under the People block, respectively.  I looked through the code for these methods (they're called as methods in ShowPeople and didn't find them declared, in the strict send (i.e. sub AdminRoleGroup {).  I did, however, find them defined in what appears to be a dynamic fashion, though I'm not that familar with the syntax.

In Type_Overlay.pm there is a scalar named '$group_role_method' and it's used (in a closure?) as:

 *$group_role_method = sub {

If you give me some guidance, I'll dig into this further.

Ryan

**Comment by RyanFrantz** [comment]
Alright.  So now I understand typeglobs (re: *$group_role_method).  As I suspected, you've got dynamic subroutines/methods in place.  All good.  I've run further tests by updating my group and user permissions in several combinations to ensure that my account has _all_ available asset-related rights assigned but I still have an issue where the object defined by $group doesn't get set.

The only way I can see my assets is if I grant myself the 'SuperUser' right.  I'd prefer to stay away from that.  Again, if you give me some additional guidance on how AT is functioning with respect to my issue, I'll assist in any way I can.

**Comment by RyanFrantz** [comment]
There is definitely something going wrong in the ACE/ACL setup/checking for this function.  If I comment out the checks (CurrentUserHasRight()) in Type_Overlay.pm I can display the Admin and Owner just fine but I can't see my custom fields.  Digging deeper...

**Comment by RyanFrantz** [comment]
Scrap all of the above.  I was working from the wrong perspective.  I'm using group rights to control access to resources in RT and somehow I completely missing setting the appropriate rights under Tools -> Configuration -> Global -> Group Rights -> <myGroup>.

My apologies; I've got this working properly.

**Comment by olaadejnr** [comment]
Hi RyanFrantz ,

From the description of your issue above, you seems to get asset tracker working on RT4. I have installed asset tracker on RT4. It installed successfully without any error messages but I don't get any UI on the RT web pages.

I heard asset tracker is not yet compactible with RT4 but it seem you had a patch for it. 

Could you please help me out here?
