### ISSUE TITLE
how to change default assest status

### ISSUE THREAD

**Issue by azuercher** [AssetTracker/rt-extension-assettracker#8]
I have a fresh install of AT 2.0 b2 on RT 3.8.10.  I would like to remove/change the default status columns (   development     dr  pilot   production  qa  test    all)  to shorten the list and align with our environment.  Is it possible to edit those and how does one go about this?   

Also, if there is a better place to ask questions please let me know.  I have found numerous RT sites spread across the web and most are dead or outdated so this seems most current.

Aaron

**Comment by chakatodd** [comment]
I prefer people use the Google group to ask questions. It doesn't get hardly any traffic, but I would like that to change.

http://groups.google.com/group/at-users

**Comment by azuercher** [comment]
thanks.  I will repost there.
