### ISSUE TITLE
Asset History brakes on first entry that has a custom field.

### ISSUE THREAD

**Issue by pr3sidentspence** [AssetTracker/rt-extension-assettracker#9]
RT4.0.2
AT 2.0.0_2

Asset History is displayed until the first time a customfield is mentioned, then it reports:

Can't call method "new" on an undefined value at /opt/rt4/sbin/../lib/RT/ObjectCustomFieldValue.pm line 304.

I was using AT2 on RT3.8.9 before this and did not see this problem.

**Comment by dentm42** [comment]
I've seen this same behavior.  I haven't been able to track down what is causing it but I'm hoping to be able to dig into it again.  Since I'm not super familiar with the code, if anyone has any pointers on where to begin digging, it'd be helpful.

**Comment by dentm42** [comment]
That was easier than expected (I had looked before for about 2 hours... this time, the answer was found quickly).  The issue is in the file: local/plugins/RTx-AssetTracker/lib/RTx/AssetTracker/Transaction_Overlay.pm

The following patch seems to resolve it for me.  The changes are taken from RT4's lib/RT/Transaction.pm since it seemed most of the original code derives or was copied from there.

<pre>
728c728,730
&lt;     if (my $type = $self-&gt;__Value('ReferenceType')) {
---
&gt;     if ( my $type = $self->__Value('ReferenceType')
&gt;          and my $id = $self->__Value('OldReference') )
&gt;     {
997a1000
&gt; 
1001a1005
&gt;             $field = $self->loc('a custom field') if !defined($field);
1004,1008c1008,1009
&lt;         if ( (not defined $self-&gt;OldValue) or ($self->OldValue eq '') ) {
&lt;             return ( $self-&gt;loc("[_1] [_2] added", $field, $self->NewValue) );
&lt;         }
&lt;         elsif ( (not defined $self-&gt;NewValue) or ($self->NewValue eq '') ) {
&lt;             return ( $self-&gt;loc("[_1] [_2] deleted", $field, $self->OldValue) );
---
&gt;         my $new = $self->NewValue;
&gt;         my $old = $self->OldValue;
1009a1011,1015
&gt;         if ( !defined($old) || $old eq '' ) {
&gt;             return $self->loc("[_1] [_2] added", $field, $new);
&gt;         }
&gt;         elsif ( !defined($new) || $new eq '' ) {
&gt;             return $self->loc("[_1] [_2] deleted", $field, $old);
1012c1018
&lt;             return $self-&gt;loc("[_1] [_2] changed to [_3]", $field, $self->OldValue, $self->NewValue );
---
&gt;             return $self->loc("[_1] [_2] changed to [_3]", $field, $old, $new);
</pre>


Note: I even figured out how to make this look right on GitHub this time! ;)

**Comment by pr3sidentspence** [comment]
Hi Matt,

How does one read apply this? I'm having trouble understanding exactly what to change. Or is it input for an editor?

Thanks,
Mike

**Comment by pr3sidentspence** [comment]
Nevermind, patch originalFile patchFile , thanks.

**Comment by pr3sidentspence** [comment]
Seems to improve things. I still get the error in some cases, though. Will look into what's different about the assets that still error tomorrow.

Thanks!

**Comment by pr3sidentspence** [comment]
So things seem much better, but like I said, I still get the error sometimes. Here are the transactions for one of our assets which still gives the error:

<pre>
mysql> select * from rt3.Transactions where ObjectId like '1709';
+--------+--------------------------+----------+-----------+-------------+--------------+-------------------------------------+-------------------------------------+----------------------------+--------------+--------------+------+---------+---------------------+
| id     | ObjectType               | ObjectId | TimeTaken | Type        | Field        | OldValue                            | NewValue                            | ReferenceType              | OldReference | NewReference | Data | Creator | Created             |
+--------+--------------------------+----------+-----------+-------------+--------------+-------------------------------------+-------------------------------------+----------------------------+--------------+--------------+------+---------+---------------------+
|   3100 | RT::Group                |     1709 |         0 | Create      | NULL         | NULL                                | NULL                                | NULL                       |         NULL |         NULL | NULL |       1 | 2009-08-09 20:12:00 |
|   7806 | RTx::AssetTracker::Asset |     1709 |         0 | Create      | NULL         | NULL                                | NULL                                | NULL                       |         NULL |         NULL | NULL |       1 | 2009-08-09 20:13:02 |
|  19722 | RTx::AssetTracker::Asset |     1709 |         0 | AddLink     | HasComponent | NULL                                | at://rt.lib.umanitoba.ca/asset/3316 | NULL                       |         NULL |         NULL | NULL |       1 | 2009-08-18 14:41:51 |
|  21923 | RTx::AssetTracker::Asset |     1709 |         0 | AddLink     | HasComponent | NULL                                | at://rt.lib.umanitoba.ca/asset/762  | NULL                       |         NULL |         NULL | NULL |       1 | 2009-08-18 17:31:51 |
|  74845 | RTx::AssetTracker::Asset |     1709 |         0 | CustomField | 8            | NULL                                | NULL                                | RT::ObjectCustomFieldValue |         NULL |        31180 | NULL |      12 | 2010-04-06 20:05:49 |
|  74846 | RTx::AssetTracker::Asset |     1709 |         0 | CustomField | 9            | NULL                                | NULL                                | RT::ObjectCustomFieldValue |         6908 |        31181 | NULL |      12 | 2010-04-06 20:05:49 |
| 154945 | RTx::AssetTracker::Asset |     1709 |         0 | DeleteLink  | HasComponent | at://rt.lib.umanitoba.ca/asset/762  | NULL                                | NULL                       |         NULL |         NULL | NULL |       1 | 2011-11-17 14:47:23 |
| 154948 | RTx::AssetTracker::Asset |     1709 |         0 | Status      | Status       | production                          | storage                             | NULL                       |         NULL |         NULL |      |     207 | 2011-11-17 14:51:49 |
| 154949 | RTx::AssetTracker::Asset |     1709 |         0 | DelWatcher  | Owner        | 341                                 | NULL                                | NULL                       |         NULL |         NULL |      |     207 | 2011-11-17 14:51:49 |
| 154950 | RTx::AssetTracker::Asset |     1709 |         0 | DeleteLink  | HasComponent | at://rt.lib.umanitoba.ca/asset/3316 | NULL                                | NULL                       |         NULL |         NULL |      |     207 | 2011-11-17 14:51:49 |
| 154952 | RTx::AssetTracker::Asset |     1709 |         0 | CustomField | 9            | NULL                                | NULL                                | RT::ObjectCustomFieldValue |        31181 |         NULL |      |     207 | 2011-11-17 14:51:49 |
| 154953 | RTx::AssetTracker::Asset |     1709 |         0 | CustomField | 8            | NULL                                | NULL                                | RT::ObjectCustomFieldValue |        31180 |        44209 |      |     207 | 2011-11-17 14:51:49 |
+--------+--------------------------+----------+-----------+-------------+--------------+-------------------------------------+-------------------------------------+----------------------------+--------------+--------------+------+---------+---------------------+
12 rows in set (0.31 sec)
</pre>

And here is the history displayed for it:

<pre>
#   Sun Aug 09 15:13:02 2009     RT_System - Asset created  
#   Tue Aug 18 09:41:51 2009     RT_System - Componet asset #3316 130.179.201.29 added  
#   Tue Aug 18 12:31:51 2009     RT_System - Componet asset #762 PAR06845 added 
#   Tue Apr 06 15:05:49 2010     root - LibraryUnit William R. Newman (Agriculture) Library added   
#   Tue Apr 06 15:05:49 2010     root - Location Agriculture Library changed to William R. Newman Library (Agriculture) 
#   Thu Nov 17 08:47:23 2011     RT_System - Componet asset #762 PAR06845 deleted   
#   Thu Nov 17 08:51:49 2011     xxxx- Status changed from production to storage    
#   Thu Nov 17 08:51:49 2011     xxxx - Owner yyyy deleted  
#   Thu Nov 17 08:51:49 2011     xxxx- Componet asset #3316 130.179.201.29 deleted  
Can't call method "new" on an undefined value at /opt/rt4/sbin/../lib/RT/ObjectCustomFieldValue.pm line 304.
</pre>

As you can see, the transaction that seems to produce the error is for custom field 9. Although custom field 9 was displayed fine earlier in the history. The only difference that I can see is that the reference for the custom field changes in the brokenly displayed one.

**Comment by pr3sidentspence** [comment]
I've looked at some more... it's when my custom field 9 changes its reference from something to NULL that the error is shown.

My custom field 9 is as follows:

<pre>
|  9 | Location        | Freeform |         1 |         |        0 |                                        |         0 | RTx::AssetTracker::Type-RTx::AssetTracker::Asset |      12 | 2009-07-16 20:01:41 |            12 | 2009-08-09 20:32:48 |        0 |    NULL | NULL       | NULL        |
</pre>


Mike

*Update also happens with other custom fields when the reference changes from something to NULL.  In both cases I've seen, so far, they have been freeform custom fields.

**Comment by dentm42** [comment]
That makes a bit of sense... since I only modified the subroutine for "OldValue".  I think the fix would be to mirror the change in OldValue (about lines 726-728) in NewValue (starting about line 740).  The important thing would be to add:

<pre>
and my $id = $self->__Value('NewReference')
</pre>


into the if statement (should be about line 742.

Obviously - backup the original and test thoroughly, but I'm thinking that should do it.

--Matt

**Comment by dentm42** [comment]
If the above doesn't fix it... drop a note.  The use cases I found where I thought it didn't fix it actually resulted because I didn't clear the mason cache (doh!).  So if there are some cases I missed, let me know and I'll dig more deeply.

-- Matt

**Comment by pr3sidentspence** [comment]
Looks good!

**Comment by smc-it** [comment]
I'm having the same problem with RT 4.0.4 and the current rt-extension-assettracker:

Can't call method "new" on an undefined value at /opt/rt4/sbin/../lib/RT/ObjectCustomFieldValue.pm line 304.

I did not notice the problem on RT 3.8.7 and the current rt-extension-assettracker.

**Comment by dentm42** [comment]
As far as I know, the patch hasn't made it into the release yet, so you'll need to apply the patch/make the changes noted above.  

-- Matt

**Comment by smc-it** [comment]
Unfortunately, this patch does not work with RT 4.0.4:

root@LinuxRT:/opt/rt4/lib/RT# patch Transaction.pm Transaction.patch
patching file Transaction.pm
Reversed (or previously applied) patch detected!  Assume -R? [n]
Apply anyway? [n] y
Hunk # 1 FAILED at 728.
Hunk # 2 succeeded at 1362 (offset 364 lines).
Hunk # 3 succeeded at 1367 (offset 364 lines).
Hunk # 4 FAILED at 1006.
Hunk # 5 succeeded at 1376 (offset 364 lines).
Hunk # 6 FAILED at 1019.
3 out of 6 hunks FAILED -- saving rejects to file Transaction.pm.rej

-----Original Message-----
